
services:
  web:
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5001
      - FLASK_APP=app.interface:create_app
    command: flask run --host=0.0.0.0 --port=5001 --reload
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "5001:5001"
    stdin_open: true
    tty: true
    build:
      context: .
    entrypoint: >
      /bin/sh -c "pip install -r requirements-dev.txt &&
                  flask run --host=0.0.0.0 --port=5001 --reload"
