services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    image: atchiullia/quitador-web:v7
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - FLASK_APP=app.interface:create_app
    ports:
      - "5001:5001"
    depends_on:
      - redis
