version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
