services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    image: atchiullia/quitador-web:v8
    environment:
      - REDIS_HOST=redis
    ports:
      - "80:80"
    depends_on:
      - redis
